# App
spring.application.name=Paballo

# H2 Database
spring.datasource.url=jdbc:h2:mem:enviro365db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# === JWT Configuration ===
app.jwt-secret=256c41a23bddbb0e21ebee12203c44109a3f55dcdee8f047a6d22f6afc8c239d
app.jwt-expiration=86400000
